DROP TABLE IF EXISTS todos CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users(
  id SERIAL PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  avatar VARCHAR(255)
);

CREATE TABLE todos(
  id SERIAL PRIMARY KEY,
  task VARCHAR(255) NOT NULL,
  user_id integer REFERENCES users(id) ON DELETE CASCADE,
  completed BOOLEAN DEFAULT false
);

